site_name: User Behavior Insights
site_url: https://www.ubisearch.dev
theme:
  name: material
  palette:
    primary: blue
nav:
  - Home: index.md
  - News: news.md
  - Quick Start: quickstart.md
  - The UBI Standard: standard.md
  - UBI Tools and Plugins: tools.md
  - Datasets: datasets.md
  - Get Involved: get_involved.md
  - Help: help.md
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/o19s/ubi
  generator: false
copyright: Copyright &copy; 2024 OpenSource Connections
repo_url: https://github.com/o19s/ubi
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
